const info = {
    SERVICE: "FMAVTS-VehicleMicroService",
    VEHICLE_REGESTRATION_SUCCESS: "Vehicle Regestration successfull",
    VEHICLE_REGESTRATION_FAIL: "Vehicle regestration failed",
    SEARCH_VEHICLE_INFO: "Vehicle Information Lookup",
    VEHICLE_NOT_FOUND: "Vehicle not found for the specified Vehicle ID",
    VEHICLE_UPDATE_SUCCESS: "user profile updation success",
    VEHICLE_UPDATE_FAIL: "user profile update failed",
    VEHICLE_RETIRED: "The vehicle record has been marked as retired",
    VEHICLE_RETIRE_FAILED: "Unable to retire the vehicle",
    ACCESS_DENIED: "You do not have the required permissions to perform this action; please contact support or an administrator for assistance if you believe this is an error",
    ERR_VEHICLE_DATA: "error fetching vehicle data",
    ERROR_VALIDATING_ROLE: "Role validation failed due to issue at server Please try again after some time",
    ROLE_VALIDATION: "user role validation success",
    ROLE_VALIDATION_FAIL: "user role validation failed",
    retirementStatus: "Vehicle successfully retired",
    VEHICLE_STATUS_LOOKUP: "Vehicle status lookup",
    VEHICLE_ASSIGNMENT_COMPLETED: "Vehicle assignment to driver completed successfully",
    VEHICLE_UNASSIGNMENT_COMPLETED: "Vehicle unassignment from driver completed successfully",
    VEHICLE_UNASSIGNMENT_ASSIGN_FAIL: "Vehicle unassignment/assignment to driver failed",
    TOKEN_UNDEFINED: "Authentication token missing or improperly formatted. Please log in and try again.",
    TOKEN_EXPIRED: "Your authentication token has expired or is malformed. Please log in again to continue.",
    ASSIGN: "assign",
    UNASSIGN: "Unassign",
    VSTATUS: "Active",
    VIASTATUS: "In-Active",
    CONN_USER_SERVICE: "Initiating connection to User Service....",
    CONN_USER_SERVICE_SUCC: "User data successfully retrieved from User Service",
    CONN_USER_SERVICE_FAIL: "User Service communication failed — terminating request",
    DRIVER_STATUS: "active",
    DRIVER_ASSIGNMENT_FAIL: "Driver allocation rejected: driver is currently engaged with another vehicle or inactive for the day.",
    DRIVER_ASSIGNMENT_SUCCESS: "Driver assignment operation completed successfully.",
    VEHCILE_STATUS_NOT_ACTIVE: "Assignment failed — the driver cannot be assigned to an inactive vehicle.",
    QUEUE_CONN_SUCESS: "Queue connection successfull",
    USER_EVENT: "Vehicle assignment details to driver service sent successfully",
    DRIVER_MSG_QUEUE: "Publish-Vehicle-Details",
    QUEUE_CON_FAIL: "Connection to message-queue Failed",
    QUEUE_CON_CLOSE: "Queue Connection closed",
    VEHICLE_WITH_TRIP_DATA: "Vehicle Details has been updated with latest trip data",
    VEHICLE_WITH_TRIP_DATA_FAIL:"Cannot update trips details to the vehicle, Please try again",
    TRIP_DATA_SYNC: "Trip data has been received successfully from trip service",
    TRIP_SYNC_SUCC: "Trip data has been synced successfully with associated vehicle",
    TRIP_SYNC_FAIL: "Unable to sync trip data with the vehicle",
    MAINTENANCE_DATA_CHECK_SUCCESS:"vehicles details fetched successfully",
    MAINTENANCE_DATA_CHECK:"fetching the vehiles that are under maintenance",
    MAINTENANCE_DATA_CHECK_FAIL:"Unable to fetch vehicles data that are under maintenance"
}

module.exports = info;